/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  darkMode: 'selector',
  theme: {
    extend: {
      colors: {
        brand: {
          950: 'rgb(var(--brand-950) / <alpha-value>)',
          900: 'rgb(var(--brand-900) / <alpha-value>)',
          800: 'rgb(var(--brand-800) / <alpha-value>)',
          700: 'rgb(var(--brand-700) / <alpha-value>)',
          600: 'rgb(var(--brand-600) / <alpha-value>)',
          500: 'rgb(var(--brand-500) / <alpha-value>)',
          400: 'rgb(var(--brand-400) / <alpha-value>)',
          300: 'rgb(var(--brand-300) / <alpha-value>)',
          200: 'rgb(var(--brand-200) / <alpha-value>)',
          100: 'rgb(var(--brand-100) / <alpha-value>)',
          50: 'rgb(var(--brand-50) / <alpha-value>)',
        },
        primary: {
          DEFAULT: 'rgb(var(--primary) / <alpha-value>)',
          hover: 'rgb(var(--primary-hover) / <alpha-value>)',
          active: 'rgb(var(--primary-active) / <alpha-value>)',
          subtle: 'rgb(var(--primary-subtle) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent) / <alpha-value>)',
          hover: 'rgb(var(--accent-hover) / <alpha-value>)',
          active: 'rgb(var(--accent-active) / <alpha-value>)',
          subtle: 'rgb(var(--accent-subtle) / <alpha-value>)',
          foreground: 'rgb(var(--accent-foreground) / <alpha-value>)',
        },
        surface: {
          DEFAULT: 'rgb(var(--surface) / <alpha-value>)',
          subtle: 'rgb(var(--surface-subtle) / <alpha-value>)',
          muted: 'rgb(var(--surface-muted) / <alpha-value>)',
          raised: 'rgb(var(--surface-raised) / <alpha-value>)',
          inverse: 'rgb(var(--surface-inverse) / <alpha-value>)',
        },
        ink: {
          DEFAULT: 'rgb(var(--ink) / <alpha-value>)',
          strong: 'rgb(var(--ink-strong) / <alpha-value>)',
          muted: 'rgb(var(--ink-muted) / <alpha-value>)',
          subtle: 'rgb(var(--ink-subtle) / <alpha-value>)',
          inverse: 'rgb(var(--ink-inverse) / <alpha-value>)',
        },
        border: {
          DEFAULT: 'rgb(var(--border) / <alpha-value>)',
          strong: 'rgb(var(--border-strong) / <alpha-value>)',
          subtle: 'rgb(var(--border-subtle) / <alpha-value>)',
          focus: 'rgb(var(--border-focus) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--success) / <alpha-value>)',
          strong: 'rgb(var(--success-strong) / <alpha-value>)',
          subtle: 'rgb(var(--success-subtle) / <alpha-value>)',
          foreground: 'rgb(var(--success-foreground) / <alpha-value>)',
          soft: 'rgb(var(--success-subtle) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--warning-subtle) / <alpha-value>)',
          200: 'rgb(var(--warning-subtle) / <alpha-value>)',
          DEFAULT: 'rgb(var(--warning) / <alpha-value>)',
          strong: 'rgb(var(--warning-strong) / <alpha-value>)',
          subtle: 'rgb(var(--warning-subtle) / <alpha-value>)',
          foreground: 'rgb(var(--warning-foreground) / <alpha-value>)',
          soft: 'rgb(var(--warning-subtle) / <alpha-value>)',
        },
        danger: {
          DEFAULT: 'rgb(var(--danger) / <alpha-value>)',
          strong: 'rgb(var(--danger-strong) / <alpha-value>)',
          subtle: 'rgb(var(--danger-subtle) / <alpha-value>)',
          foreground: 'rgb(var(--danger-foreground) / <alpha-value>)',
        },
        info: {
          DEFAULT: 'rgb(var(--info) / <alpha-value>)',
          strong: 'rgb(var(--info-strong) / <alpha-value>)',
          subtle: 'rgb(var(--info-subtle) / <alpha-value>)',
          foreground: 'rgb(var(--info-foreground) / <alpha-value>)',
        },
        maintenance: {
          ok: 'rgb(var(--maintenance-ok) / <alpha-value>)',
          due: 'rgb(var(--maintenance-due) / <alpha-value>)',
          overdue: 'rgb(var(--maintenance-overdue) / <alpha-value>)',
          scheduled: 'rgb(var(--maintenance-scheduled) / <alpha-value>)',
          inactive: 'rgb(var(--maintenance-inactive) / <alpha-value>)',
        },
      },
      boxShadow: {
        card: '0 1px 2px rgb(var(--shadow-rgb) / 0.04), 0 8px 24px rgb(var(--shadow-rgb) / 0.05)',
        sidebar: '8px 0 24px rgb(var(--shadow-rgb) / 0.16)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
