<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Importaciones - Mantenimiento</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"></head>
<body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container d-flex gap-2"><a class="navbar-brand" href="<?= base_url('dashboard') ?>">Mantenimiento</a><a class="btn btn-outline-light btn-sm ms-auto" href="<?= base_url('mantenimiento/equipos') ?>">Equipos</a><form method="post" action="<?= base_url('logout') ?>" class="mb-0"><?= csrf_field() ?><button class="btn btn-outline-light btn-sm">Cerrar sesión</button></form></div></nav>
<main class="container py-4">
    <header class="mb-4"><p class="text-primary fw-semibold mb-1">Anti-Corruption Layer</p><h1 class="h3">Importaciones</h1><p class="text-muted">Cargá un CSV/XLSX, revisá los errores por fila y confirmá explícitamente.</p></header>
    <?php if (session()->getFlashdata('success')): ?><div class="alert alert-success" role="status"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
    <?php if (session()->getFlashdata('error')): ?><div class="alert alert-danger" role="alert"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
    <?php if ($canUpload): ?><section class="card shadow-sm mb-4"><div class="card-header"><h2 class="h5 mb-0">Nueva importación</h2></div><div class="card-body">
        <div class="mb-3"><a class="btn btn-sm btn-outline-secondary" href="<?= base_url('mantenimiento/importaciones/plantilla/EQUIPOS') ?>">Plantilla de equipos</a> <a class="btn btn-sm btn-outline-secondary" href="<?= base_url('mantenimiento/importaciones/plantilla/LECTURAS') ?>">Plantilla de lecturas</a></div>
        <form method="post" enctype="multipart/form-data" action="<?= base_url('mantenimiento/importaciones') ?>" class="row g-3"><?= csrf_field() ?><div class="col-sm-3"><label class="form-label" for="import-type">Tipo</label><select class="form-select" id="import-type" name="tipo"><option value="EQUIPOS">Equipos</option><option value="LECTURAS">Lecturas</option></select></div><div class="col-sm-6"><label class="form-label" for="import-file">Archivo CSV o XLSX</label><input class="form-control" id="import-file" type="file" name="archivo" accept=".csv,.xlsx" required><div class="form-text">Máximo <?= esc((int) env('imports.maxSizeMB', 10)) ?> MB y 5.000 filas.</div></div><div class="col-sm-3 d-flex align-items-end"><button class="btn btn-primary w-100" type="submit">Validar archivo</button></div></form>
    </div></section><?php endif; ?>
    <section class="card shadow-sm"><div class="card-header d-flex justify-content-between"><h2 class="h5 mb-0">Historial</h2><span class="badge text-bg-secondary"><?= esc($imports->total) ?></span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Fecha</th><th>Archivo</th><th>Resultado</th><th>Estado</th><th></th></tr></thead><tbody>
    <?php foreach ($imports->items as $item): ?><tr><td><?= esc($item['fecha']) ?><br><span class="small text-muted"><?= esc($item['usuario_nombre'] ?? 'Usuario') ?></span></td><td><?= esc($item['archivo_original']) ?><br><span class="badge text-bg-light"><?= esc($item['tipo']) ?></span></td><td><?= esc($item['filas_importadas']) ?> importadas · <?= esc($item['filas_error']) ?> errores · <?= esc($item['filas_duplicadas']) ?> duplicadas<br><span class="small text-muted"><?= esc($item['resumen'] ?? '') ?></span></td><td><span class="badge text-bg-info"><?= esc($item['estado']) ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?= base_url('mantenimiento/importaciones/' . $item['id']) ?>">Ver detalle</a></td></tr><?php endforeach; ?>
    <?php if ($imports->items === []): ?><tr><td colspan="5" class="text-muted text-center py-4">Todavía no hay importaciones dentro de tu alcance.</td></tr><?php endif; ?>
    </tbody></table></div><?php $totalPages = max(1, (int) ceil($imports->total / $imports->perPage)); if ($totalPages > 1): ?><div class="card-footer d-flex justify-content-between"><a class="btn btn-sm btn-outline-secondary <?= $imports->page <= 1 ? 'disabled' : '' ?>" href="?page=<?= max(1, $imports->page - 1) ?>">Anterior</a><span class="small text-muted">Página <?= esc($imports->page) ?> de <?= esc($totalPages) ?></span><a class="btn btn-sm btn-outline-secondary <?= $imports->page >= $totalPages ? 'disabled' : '' ?>" href="?page=<?= min($totalPages, $imports->page + 1) ?>">Siguiente</a></div><?php endif; ?></section>
</main></body></html>
