<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Vista previa de importación - Mantenimiento</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"></head>
<body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="<?= base_url('dashboard') ?>">Mantenimiento</a><a class="btn btn-outline-light btn-sm ms-auto" href="<?= base_url('mantenimiento/importaciones') ?>">Volver</a></div></nav>
<main class="container py-4">
    <?php $header = $preview->header; ?>
    <header class="mb-4"><p class="text-primary fw-semibold mb-1">Vista previa #<?= esc($header['id']) ?></p><h1 class="h3 mb-1"><?= esc($header['archivo_original']) ?></h1><p class="text-muted"><?= esc($header['tipo']) ?> · <?= esc($header['estado']) ?> · <?= esc($header['resumen'] ?? '') ?></p></header>
    <?php if (session()->getFlashdata('success')): ?><div class="alert alert-success" role="status"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
    <?php if (session()->getFlashdata('error')): ?><div class="alert alert-danger" role="alert"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
    <div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="card"><div class="card-body"><span class="small text-muted">Total</span><div class="h4 mb-0"><?= esc($header['filas_totales']) ?></div></div></div></div><div class="col-6 col-lg-3"><div class="card"><div class="card-body"><span class="small text-muted">Válidas</span><div class="h4 mb-0 text-success"><?= esc($header['filas_validas']) ?></div></div></div></div><div class="col-6 col-lg-3"><div class="card"><div class="card-body"><span class="small text-muted">Errores</span><div class="h4 mb-0 text-danger"><?= esc($header['filas_error']) ?></div></div></div></div><div class="col-6 col-lg-3"><div class="card"><div class="card-body"><span class="small text-muted">Duplicadas</span><div class="h4 mb-0 text-warning"><?= esc($header['filas_duplicadas']) ?></div></div></div></div></div>
    <?php if ($canMutate && $header['estado'] === 'BORRADOR_VALIDADO'): ?><div class="d-flex gap-2 mb-4"><form method="post" action="<?= base_url('mantenimiento/importaciones/' . $header['id'] . '/confirmar') ?>" onsubmit="return confirm('¿Confirmás la persistencia de las filas válidas?');"><?= csrf_field() ?><button class="btn btn-success" type="submit" <?= (int) $header['filas_validas'] === 0 ? 'disabled' : '' ?>>Confirmar importación</button></form><form method="post" action="<?= base_url('mantenimiento/importaciones/' . $header['id'] . '/cancelar') ?>"><?= csrf_field() ?><button class="btn btn-outline-danger" type="submit">Cancelar borrador</button></form></div><?php endif; ?>
    <section class="card shadow-sm"><div class="card-header d-flex justify-content-between"><h2 class="h5 mb-0">Filas validadas</h2><span class="badge text-bg-secondary"><?= esc($preview->total) ?></span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Fila</th><th>Estado</th><th>Datos normalizados</th><th>Errores/resultado</th></tr></thead><tbody>
    <?php foreach ($preview->rows as $row): ?><tr><td>#<?= esc($row['numero_fila']) ?></td><td><span class="badge text-bg-<?= $row['estado'] === 'VALIDA' || $row['estado'] === 'IMPORTADA' ? 'success' : ($row['estado'] === 'DUPLICADA' ? 'warning' : 'danger') ?>"><?= esc($row['estado']) ?></span></td><td><pre class="small mb-0 text-wrap"><?= esc(json_encode($row['datos_normalizados'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) ?></pre></td><td><?php foreach ($row['errores'] as $issue): ?><div class="small"><strong><?= esc($issue['campo']) ?>:</strong> <?= esc($issue['mensaje']) ?></div><?php endforeach; ?><?= $row['resultado'] ? '<div class="small">' . esc($row['resultado']) . '</div>' : '' ?></td></tr><?php endforeach; ?>
    <?php if ($preview->rows === []): ?><tr><td colspan="4" class="text-muted text-center py-4">No hay filas visibles en tu alcance.</td></tr><?php endif; ?>
    </tbody></table></div><?php $totalPages = max(1, (int) ceil($preview->total / $preview->perPage)); if ($totalPages > 1): ?><div class="card-footer d-flex justify-content-between"><a class="btn btn-sm btn-outline-secondary <?= $preview->page <= 1 ? 'disabled' : '' ?>" href="?page=<?= max(1, $preview->page - 1) ?>">Anterior</a><span class="small text-muted">Página <?= esc($preview->page) ?> de <?= esc($totalPages) ?></span><a class="btn btn-sm btn-outline-secondary <?= $preview->page >= $totalPages ? 'disabled' : '' ?>" href="?page=<?= min($totalPages, $preview->page + 1) ?>">Siguiente</a></div><?php endif; ?></section>
</main></body></html>
