export const csrf = { name: 'csrf_test_name', hash: 'secure-token' }

export const superAdminData = {
  csrf,
  flash: { success: 'Empresa creada.', error: '' },
  permissions: { companiesEdit: true, createCompanyAdministrators: true, assignCompanies: true, assignRoles: true },
  metrics: { companiesTotal: 2, companiesActive: 1, usersTotal: 2 },
  actions: {
    createCompany: '/superadmin/empresas',
    createCompanyAdministrator: '/superadmin/administradores',
  },
  oldInput: {
    razon_social: '', nombre_fantasia: '', cuit: '', email: '', telefono: '',
    admin_empresa_id: 1, admin_nombre: 'Nueva administradora', admin_email: '', admin_motivo: '',
  },
  companies: [
    {
      id: 1,
      razonSocial: 'Transportes Sur SA',
      nombreFantasia: 'Transportes Sur',
      displayName: 'Transportes Sur',
      cuit: '30-12345678-9',
      email: 'admin@transportes.test',
      telefono: '3415550000',
      active: true,
      actions: { update: '/superadmin/empresas/1' },
    },
    {
      id: 2,
      razonSocial: 'Empresa Norte SA',
      nombreFantasia: '',
      displayName: 'Empresa Norte SA',
      cuit: '',
      email: '',
      telefono: '',
      active: false,
      actions: { update: '/superadmin/empresas/2' },
    },
  ],
  assignableCompanies: [{ id: 1, name: 'Transportes Sur SA' }],
  roles: [
    { id: 1, name: 'Administrador', description: '' },
    { id: 2, name: 'Responsable de mantenimiento', description: '' },
  ],
  users: [
    {
      id: 1,
      name: 'Super Admin',
      email: 'superadmin@mantenimiento.local',
      active: true,
      isSuperAdmin: true,
      companyId: '',
      companyName: '',
      roles: [],
      assignedRoleIds: [],
      actions: { assignCompany: '', assignRoles: '' },
    },
    {
      id: 2,
      name: 'Ana Administradora',
      email: 'ana@transportes.test',
      active: true,
      isSuperAdmin: false,
      companyId: 1,
      companyName: 'Transportes Sur SA',
      roles: [{ id: 1, name: 'Administrador', description: '' }],
      assignedRoleIds: [1],
      actions: {
        assignCompany: '/superadmin/usuarios/2/empresa',
        assignRoles: '/superadmin/usuarios/2/roles',
      },
    },
  ],
}

export const branchesAdminData = {
  csrf,
  flash: { success: '', error: '' },
  company: { id: 1, name: 'Transportes Sur SA' },
  permissions: { edit: true },
  metrics: { total: 2, active: 1, inactive: 1 },
  actions: { create: '/administracion/sucursales' },
  oldInput: { codigo: 'ROS', nombre: '', direccion: '', emailAlertas: '' },
  branches: [
    {
      id: 4,
      code: 'CENTRO',
      name: 'Sucursal Centro',
      address: 'Calle 123',
      alertEmail: 'alertas@transportes.test',
      active: true,
      actions: { update: '/administracion/sucursales/4' },
    },
    {
      id: 5,
      code: 'NORTE',
      name: 'Sucursal Norte',
      address: '',
      alertEmail: '',
      active: false,
      actions: { update: '/administracion/sucursales/5' },
    },
  ],
}

export const usersAdminData = {
  csrf,
  flash: { success: '', error: '' },
  company: { id: 1, name: 'Transportes Sur SA' },
  permissions: { create: true, editAccounts: true, editAccess: true, resetPasswords: true },
  metrics: { total: 2, active: 2, inactive: 0 },
  actions: { create: '/administracion/usuarios' },
  oldInput: { nombre: '', email: '', motivo: '', roleIds: [2], branchIds: [4] },
  roles: [
    { id: 1, name: 'Administrador', description: '' },
    { id: 2, name: 'Técnico u operador', description: '' },
  ],
  assignableBranches: [
    { id: 4, code: 'CENTRO', name: 'Sucursal Centro' },
    { id: 6, code: 'SUR', name: 'Sucursal Sur' },
  ],
  users: [
    {
      id: 2,
      name: 'Ana Administradora',
      email: 'ana@transportes.test',
      active: true,
      isSelf: true,
      canDeactivate: false,
      allCompanyBranches: true,
      lastAccess: '08/08/2026 10:30',
      roles: [{ id: 1, name: 'Administrador', description: '' }],
      branches: [],
      assignedRoleIds: [1],
      assignedBranchIds: [],
      actions: {
        update: '/administracion/usuarios/2',
        assignAccess: '/administracion/usuarios/2/acceso',
        resetPassword: '/administracion/usuarios/2/password',
      },
    },
    {
      id: 3,
      name: 'Tomás Técnico',
      email: 'tomas@transportes.test',
      active: true,
      isSelf: false,
      canDeactivate: true,
      allCompanyBranches: false,
      lastAccess: '',
      roles: [{ id: 2, name: 'Técnico u operador', description: '' }],
      branches: [{ id: 4, code: 'CENTRO', name: 'Sucursal Centro', active: true }],
      assignedRoleIds: [2],
      assignedBranchIds: [4],
      actions: {
        update: '/administracion/usuarios/3',
        assignAccess: '/administracion/usuarios/3/acceso',
        resetPassword: '/administracion/usuarios/3/password',
      },
    },
  ],
}
