export const dashboardPayload = {
  mode: 'tenant',
  user: { name: 'Ana Pérez', email: 'ana@example.test', roles: ['Administradora'], isSuperAdmin: false },
  company: { name: 'Transportes Sur', branches: [{ id: 2, name: 'Sucursal Centro' }] },
  navigation: [
    { key: 'dashboard', label: 'Dashboard', href: '/dashboard', icon: 'dashboard', active: true },
    { key: 'equipment', label: 'Camiones', href: '/mantenimiento/equipos', icon: 'truck' },
    { key: 'plans', label: 'Planes preventivos', href: '/mantenimiento/planes', icon: 'maintenance' },
  ],
  metrics: {
    equipmentTotal: 24,
    equipmentActive: 21,
    equipmentWithoutPlans: 2,
    plansConfigured: 18,
    maintenanceDueSoon: 5,
    maintenanceOverdue: 2,
    maintenanceMissingData: 1,
    maintenanceScheduled: 8,
    openOrders: 3,
  },
  links: {
    equipment: '/mantenimiento/equipos',
    equipmentCreate: '/mantenimiento/equipos#nuevo-equipo',
    maintenance: '/mantenimiento/planes',
    services: '/mantenimiento/servicios',
    assignPlan: '/mantenimiento/planes',
    registerMaintenance: '/mantenimiento/equipos',
    quickReadings: '/mantenimiento/lecturas/rapidas',
    library: '/mantenimiento/servicios',
    maintenanceDueSoon: '/mantenimiento/planes?estado=PROXIMO',
    maintenanceOverdue: '/mantenimiento/planes?estado=VENCIDO',
    maintenanceMissingData: '/mantenimiento/planes?estado=SIN_DATOS',
    orders: '/mantenimiento',
  },
  upcomingMaintenance: [
    {
      planId: 16,
      equipmentId: 10,
      equipmentCode: 'Volvo FH',
      serviceName: 'Service motor',
      branchName: 'Sucursal Centro',
      remaining: 'Vencido por 3 días',
      status: 'VENCIDO',
      statusLabel: 'Vencido',
      priority: 1,
      detailUrl: '/mantenimiento/equipos/10',
      actionUrl: '/mantenimiento/planes?equipo_id=10&estado=VENCIDO',
      actionLabel: 'Atender',
    },
    {
      planId: 15,
      equipmentId: 9,
      equipmentCode: 'Scania R450',
      serviceName: 'Cambio de aceite y filtros',
      branchName: 'Sucursal Centro',
      remaining: 'Faltan 1.200 km',
      status: 'PROXIMO',
      statusLabel: 'Próximo',
      priority: 2,
      detailUrl: '/mantenimiento/equipos/9',
      actionUrl: '/mantenimiento/planes?equipo_id=9&estado=PROXIMO',
      actionLabel: 'Ver plan',
    },
  ],
  logout: {
    url: '/logout',
    csrfName: 'csrf_test_name',
    csrfHash: 'secure-token',
  },
}